apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: do-float-ip
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: do-float-ip
    spec:
      containers:
      - image: quay.io/fivepi/do-float-ip
        name: do-float-ip
        resources:
          limits:
            cpu: 200m
            memory: 10Mi
          requests:
            cpu: 100m
            memory: 5Mi
        args:
        - 188.166.192.47
        volumeMounts:
        - name: do-token
          mountPath: /secret
      volumes:
      - name: do-token
        secret:
          secretName: default
          items:
          - key: "do-token"
            path: "do.token"
