apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: prometheus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - image: quay.io/prometheus/prometheus
        name: prometheus
        resources:
          limits:
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 350Mi
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: host-ssl
          mountPath: /etc/host-ssl
        - name: data
          mountPath: /prometheus
        args:
        - -config.file=/etc/prometheus/prometheus.yml
        - -storage.local.path=/prometheus
        - -web.console.libraries=/usr/share/prometheus/console_libraries
        - -web.console.templates=/usr/share/prometheus/consoles
        - -storage.local.memory-chunks=175000                           # ~175MB for chunks
        - -storage.local.max-chunks-to-persist=87500                    # 50% of memory chunks
        - -storage.local.chunk-encoding-version=2                       # higher CPU, less mem usage
        - -storage.local.index-cache-size.fingerprint-to-metric=5242880 # 1/2 default cache size
        - -storage.local.index-cache-size.fingerprint-to-timerange=2621440
        - -storage.local.index-cache-size.label-name-to-label-values=5242880
        - -storage.local.index-cache-size.label-pair-to-fingerprints=10485760
        - -alertmanager.url=http://prometheus-am
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
      - name: host-ssl
        hostPath:
          path: /etc/ssl
      - name: data
        flexVolume:
          driver: "5pi.de/do-volume"
          fsType: "ext4"
          options:
            volume: "prometheus"
