apiVersion: v1
kind: Service
metadata:
  name: prometheus-am
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: mesh
      port: 6783
      targetPort: mesh
  selector:
    app: prometheus-am
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-am
  labels:
    app: prometheus-am
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: prometheus-am
    spec:
      containers:
      - image: quay.io/prometheus/alertmanager:v0.5.0-alpha.0
        name: prometheus-am
        command:
        - /bin/sh
        args:
        - -c
        - 'sed "s/<SMTP_PASSWORD>/$SMTP_PASSWORD/" /etc/prometheus/alertmanager.yml.in
             > /etc/prometheus/alertmanager.yml
             && exec /bin/alertmanager -config.file /etc/prometheus/alertmanager.yml -storage.path=/alertmanager -mesh.peer prometheus-am:6783'
        ports:
        - name: http
          containerPort: 9093
        - name: mesh
          containerPort: 6783
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        env:
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: default
              key: smtp-infra-password
      volumes:
      - name: config-volume
        configMap:
          name: prometheus-config
