apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: blackbox-exporter
  labels:
    app: blackbox-exporter
spec:
  ports:
  - name: blackbox-exporter
    port: 80
    targetPort: http
  selector:
    app: blackbox-exporter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blackbox-exporter-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blackbox-exporter
        version: "v0.2.0"
    spec:
      containers:
      - name: blackbox-exporter
        image: quay.io/prometheus/blackbox-exporter:v0.2.0
        ports:
        - name: http
          containerPort: 9115
